apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - appproject.yaml
  - app-of-apps.yaml
  - external-secrets.yaml

# Common labels for ArgoCD resources
commonLabels:
  app.kubernetes.io/part-of: argocd
