apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-monitors.yaml
  - prometheus-rules.yaml

commonLabels:
  app.kubernetes.io/component: monitoring
